branch-defaults:
  managementPortal:
    environment: Telos-Management-Portal-staging
environment-defaults:
  Telos-Management-Portal-staging:
    branch: null
    repository: null
global:
  application_name: Telos-Management-Portal
  default_ec2_keyname: Telos-production
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Node.js running
    on 64bit Amazon Linux/4.4.5
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
